services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    env_file:
      - ./backend/.env
    volumes:
      - mongo-data:/data/db
      - ./backend/mongod.conf:/etc/mongo/mongod.conf
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    
  backend:
    container_name: extractta-code-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    container_name: extractta-code-frontend
    build:
      context: ./frontend
    ports:
      - '3001:80'
    depends_on:
      - backend

volumes:
  mongo-data:
